### PR TITLE
Added sequential Ids

### LINKED ISSUE #50: Backend: Add readable id's to schemas

### PR DESCRIPTION
**Pull request by navidboloorian**
### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
Added a counter schema that allows for incremental id's for simpler route access

### Testing
Inserted manually and checked against inserts

### Confirmation of Change 
Use routes to access groups based on numerical id. In the table right now exists employees with id of 0 and packages with id of 1

### CODE REVIEW

**Review by eliasfang — APPROVED** [review]
LGTM!

**Review by pratyush1718 — APPROVED** [review]
All good from my end

**Comment by kgfu02** [comment]
@navidboloorian When I try to save a TableData with group: 0 is it supposed to return an error saying "tableData validation failed: group: Path `group` is required"? For all other values it works fine.

**Comment by navidboloorian** [comment]
> @navidboloorian When I try to save a TableData with group: 0 is it supposed to return an error saying "tableData validation failed: group: Path `group` is required"? For all other values it works fine.

Can you slack me a screenshot?

**Pull request merged**
