### PR TITLE
Feature/pratyush1718/users schema

### LINKED ISSUE #4: Backend - Create users schema
- Create users schema in models folder with the following fields
- Full name (string, required, index true)
- Email (string, required, index true)
- Company id (string, required)
- Password (string, required), passwords should not be stored as raw text. Implement a function that hashes passwords on the server side
- Timestamps true

[Mongoose hashing reference](https://www.mongodb.com/blog/post/password-authentication-with-mongoose-part-1)

### PR DESCRIPTION
**Pull request by pratyush1718**
### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Created a Users schema in Users.js
- Also included hashing password function and verifying password function in Users.js
- Ran quick user test in app.js (taken out now) + schema import 

### Testing
How did you confirm your changes worked? 
- console.log()'d a sample user and verified password by printing boolean value in app.js

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
image

### CODE REVIEW

**Review by eliasfang — APPROVED** [review]
Super cool work! No changes from me ✌🏼

**Review by navidboloorian — CHANGES_REQUESTED** [review]
Good stuff Pratyush! Password hash works as intended and schema looks good. Good to merge except for the stuff in the app.js file. Good for testing to have that but now that everything's good to go it should be removed. We'll have a separate file for all the routes in a future issue.

**Comment by pratyush1718** [comment]
> Good stuff Pratyush! Password hash works as intended and schema looks good. Good to merge except for the stuff in the app.js file. Good for testing to have that but now that everything's good to go it should be removed. We'll have a separate file for all the routes in a future issue.

**Review by navidboloorian — APPROVED** [review]
LGTM!

**Pull request merged**
