### PR TITLE
Feature/alexzhang1618/style settings

### PR DESCRIPTION
**Pull request by alexzhang1618**
### Administrative Info
[GitHub Issue #17 ]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Updated Settings.css and Settings.js to style the settings page and fix linting warnings
- Updated Admin.js to resize the table to be wider if more space is needed

### Testing
How did you confirm your changes worked? 
- Ran the React App

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Settings Page |
| --- |
| Screen Shot 2022-02-23 at 2 43 08 PM |

| Admin Table |
| --- |
| Screen Shot 2022-02-23 at 2 43 29 PM |

### CODE REVIEW

**Review by navidboloorian — APPROVED** [review]
LGTM! Don't forget to fix any linting errors and rebase

**Review by kgfu02 — COMMENTED** [review]
Just checking, is the URL supposed to show the passwords or is that something that will get fixed once the backend gets linked to the form?

**Comment by alexzhang1618** [comment]
The URL will probably be fixed when the form is linked to a post request from the backend

**Review by kgfu02 — APPROVED** [review]
LGTM

**Pull request merged**
