### PR TITLE
Feature/alexzhang1618/style admin page

### PR DESCRIPTION
**Pull request by alexzhang1618**
### Administrative Info
[GitHub Issue #19]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Admin.css
    - Added positioning and formatting changes
- Admin.js
    - Added classnames and imported vector image for styling
    - Added in more dummy data
- Added images folder and AddIcon.svg for admin page styling
- Renamed Table.js and Table.css to resolve imports

### Testing
How did you confirm your changes worked? 
- Imported the admin page alongside the side navigation and ran the React app

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Admin Page and Side Navigation |
| --- |
| Screen Shot 2022-01-26 at 8 24 14 PM (2) |

### CODE REVIEW

**Review by navidboloorian — CHANGES_REQUESTED** [review]
Wow Alex really, really good stuff! Just one tweak: can you make the width of the table a max-width instead? At the moment it'll just overflow off the page if the width of the browser gets too small but it would be better if it expanded/shrank slightly with the window.

**Review by eliasfang — APPROVED** [review]
Other than Navid's changes, this looks really good! 💪🏼

**Review by navidboloorian — CHANGES_REQUESTED** [review]
Good stuff! Just rebase with master/router stuff and we can merge

**Comment by alexzhang1618** [comment]
Just rebased the branch with master! It should be good now

**Review by navidboloorian — APPROVED** [review]
Nice, go ahead and merge

**Pull request merged**
