### PR TITLE
Added react routing

### LINKED ISSUE #33: Frontend - Add router

### PR DESCRIPTION
**Pull request by navidboloorian**
### Administrative Info
#33 
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
- Added react router and made side nav link to pages

### Testing
How did you confirm your changes worked? 
- Navigated to specified pages

### Confirmation of Change 
image
/admin now leading to admin page

image
/settings now leading to settings page

image
dashboard is landing page

### CODE REVIEW

**Review by eliasfang — CHANGES_REQUESTED** [review]
Beautiful! Would it be a good idea to also fix some file names in this PR too (i.e. index.js/.css to Index.js/.css)?

**Comment by navidboloorian** [comment]
> Beautiful! Would it be a good idea to also fix some file names in this PR too (i.e. index.js/.css to Index.js/.css)?

Good catch! Will do

**Comment by navidboloorian** [comment]
Updated dashboard to Dashboard, tableData to TableData, and table to Table. Lmk if i missed any

**Review by eliasfang — APPROVED** [review]
Thanks for doing that! 🙏🏼

**Review by alexzhang1618 — APPROVED** [review]
Looks good to me!

**Pull request merged**
